apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-core
spec:
  template:
    spec:
      containers:
        - name: saleor-core
          image: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-core:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-storefront
spec:
  template:
    spec:
      containers:
        - name: saleor-storefront
          image: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-storefront:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-dashboard
spec:
  template:
    spec:
      containers:
        - name: saleor-dashboard
          image: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-dashboard:latest
